### ISSUE TITLE
Typescript error: Cannot find module 'zustand/shallow'

### ISSUE THREAD

**Issue by hugo-chq** [react-spring/zustand#156]
Hi thanks for making zustand, 
After upgrading to 3.0 the import for zustand/shallow seems to work but shows a type error
`Cannot find module 'zustand/shallow' or its corresponding type declarations.`
https://codesandbox.io/s/thirsty-dew-kru3z?file=/src/App.tsx

**Comment by drcmda** [comment]
@dai-shi there was something odd wit the types. it adds them to dist/src/... package.json has types declared as src/index.d.ts. shouldn't types be flatly within dist, without the extra src/ ?

**Comment by drcmda** [comment]
@hugo-chq should be fixed!

**Comment by dai-shi** [comment]
https://codesandbox.io/s/laughing-pare-z3ijw
works fine with v3.0.1 👍
